/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function __decode_try_json_async(
  bytes: Buffer,
  optionsJson?: string | undefined | null,
): NapiResult<Promise<unknown>>

export declare function __decode_try_json_sync(
  bytes: Buffer,
  optionsJson?: string | undefined | null,
): NapiResult<string>

export declare function __validate_json_async(
  bytes: Buffer,
  profile?: string | undefined | null,
): NapiResult<Promise<unknown>>

export declare function __validate_json_sync(bytes: Buffer, profile?: string | undefined | null): NapiResult<string>
